export default {
    welcome: "Welcome",
    username: "Username",
    password: "Password",
    login: "Login",
    doNotHaveAccount: "Do not have an account?",
    createAccount: "Create Account",
    joinUs: "Join Us",
    haveAccount: "Have an account?",
    workspaces: "workspaces",
    todayTodos: "Today Todos",
    noTodosToday: "There is no todos Today!",
    edit: "Edit",
    delete: "Delete",
    todos: "Todos",
    notes: "Notes",
    logs: "Logs",
    error404: "404 Error",
    workspaceNotFound: "Workspace not found.",
    pageNotFound: "Page not found",
    workspace: "Workspace",
    createTodo: "CreateTodo",
    createNewTodo: "Create new todo",
    submit: "Submit",
    deleteTodoMessage: "Are you sure you want yo delete this todo!",
    cancel: "Cancel",
    editTodo: "Edit Todo",
    addNewWorkspace: "Add new workspace",
    deleteWorkspaceMessage: "Are you sure you want yo delete this workspace!",
    updateWorkspace: "Update workspace",
    newWorkspace: "New Workspace",
    noTodoThisMonth: "There is no todos this month!",
    childrenWorkspaces: "Children Workspaces",
    noNotes: "There is no notes yet!",
    addNewNote: "Add new note",
    createNote: "CreateNote",
    deleteNoteMessage: "Are you sure you want yo delete this note!",
    createLog: "CreateLog",
    addNewLog: "Add new log",
    noLogsThisMonth: "There is no logs this month!",
    editLog: "Edit log",
    deleteLogMessage: "Are you sure you want yo delete this log!",
    settings: "Settings",
    updateUsername: "Update Username"
}
